# Generated by Django 3.2.9 on 2022-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_problemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlist',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
