# Generated by Django 3.2.8 on 2022-01-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_dignosticsresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dignosticsresult',
        ),
    ]
