# Generated by Django 3.2.9 on 2022-01-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_problemlist_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='problemList',
        ),
    ]
