# Generated by Django 3.2.8 on 2022-01-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_dignosticsresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='pasthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=50)),
                ('body_site', models.CharField(max_length=100)),
                ('date_of_onsite', models.DateField()),
                ('severity', models.CharField(max_length=100)),
                ('Problem_Qualifier', models.CharField(max_length=100)),
                ('diagnostic_certainty', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
            ],
        ),
    ]
