# Generated by Django 3.2.9 on 2022-01-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_plancare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planCare',
        ),
    ]
