# Generated by Django 3.2.9 on 2022-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0015_delete_plancare'),
    ]

    operations = [
        migrations.CreateModel(
            name='planCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carePlanName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
            ],
        ),
    ]
