# Generated by Django 3.2.8 on 2022-01-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
