# Generated by Django 3.2.8 on 2022-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0022_remove_patientinfo_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlist',
            name='dateOfOnset',
            field=models.CharField(max_length=100),
        ),
    ]
