# Generated by Django 3.2.8 on 2022-01-16 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0023_alter_problemlist_dateofonset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dignosticsresults',
            old_name='description',
            new_name='body_site',
        ),
        migrations.AddField(
            model_name='dignosticsresults',
            name='method_of_diagnosis',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dignosticsresults',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancare',
            name='bedrest',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancare',
            name='type_of_diet',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
